### ISSUE TITLE
Task list > Issues

### ISSUE THREAD

**Issue by jeffwade** [jeffwade/infieri#17]
Migrate task list to GitHub issues.
- [ ] HUD
  - [ ] affected property values
  - [ ] large icons(?)
- [ ] arrangement tweaks:
  - [ ] set attraction to 0
  - [ ] set position within visible walls
  - [ ] wrap around/ deal with walls
- [ ] all properties in new shape
- [ ] RANDOM
  - [ ] affected property groups: labels and new shapes

**Comment by jeffwade** [comment]
All items are now issues
